In [1]:
!pip install torch


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# create model class using normal forward function and not using sequential container 
# import torch 
# import torch.nn as nn
# class Model(nn.Module):
#     def __init__(self,num_features):
#         super().__init__()
#         self.Linear1 = nn.Linear(num_features,3)
#         self.ReLu = nn.ReLU() 
#         self.Linear2 = nn.Linear(3,1)
#         self.sigmoid = nn.Sigmoid()

#     def forward(self,features):
#         out = self.Linear1(features)
#         out = self.ReLu(out)
#         out = self.Linear2(out)
#         out = self.sigmoid(out)

#         return out

In [24]:
# using sequential container to create model class
import torch
import torch.nn as nn
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )   
    
    def forward(self,features):
        return self.network(features)

In [25]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.5550],
        [0.5570],
        [0.5530],
        [0.5768],
        [0.5614],
        [0.5788],
        [0.5560],
        [0.5591],
        [0.5455],
        [0.5617]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.Linear.weight


Parameter containing:
tensor([[-0.0883,  0.3361,  0.1870,  0.4157, -0.0029],
        [ 0.2669,  0.1791,  0.3728,  0.3712,  0.4106],
        [-0.1943,  0.4189, -0.3077, -0.0249,  0.3484]], requires_grad=True)

In [6]:
model.Linear1.bias


Parameter containing:
tensor([0.4441, 0.0928, 0.3626], requires_grad=True)

In [7]:
model.Linear2.weight

Parameter containing:
tensor([[ 0.4544,  0.2686, -0.5649]], requires_grad=True)

In [8]:
model.Linear2.bias

Parameter containing:
tensor([-0.5753], requires_grad=True)

In [9]:
!pip install torchinfo


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00